### ISSUE TITLE
Warn user if trying to replay a pcap file in raw IP format

### ISSUE THREAD

**Issue by leonexis** [appneta/tcpreplay#153] opened 2014-10-22 19:21 UTC
This really isn't a bug, more of a request. I was using the iCTF2010 pcap recording of that conference. I did not realize this at first, but that file is in Raw IP format, so it contains no L2 information. `tcpreplay` will happily play those packets over the network without the L2 information. Since `tcpdump` can determine the type of pcap file it is, it might be easy to at least warn the user that, although `tcpreplay` will happily replay the file, the packets will lack L2 data and will be treated as gibberish on the receiving end. This should probably be extended to other pcap formats that can't be replayed properly. 

The solution for converting the pcap file is very easy once the end user knows the issue:

```
tcprewrite --dlt=enet --infile=somefile.pcap --outfile=somefile-enet.pcap \
    --enet-dmac=xx:xx:xx:xx:xx:xx --enet-smac=xx:xx:xx:xx:xx:xx
```

**Comment by fklassen** [comment] 2017-03-04 17:03
@leonexis I am cleaning up my old requests. I think I understand the code well enough to take this on, but I do need a raw file.

The above links no longer exist. Do you have a smaller raw file?

**Comment by leonexis** [comment] 2017-03-06 20:54
I've looked everywhere I can think of and I can't find my copy of the pcap file, which is a shame. That was a really good set and it looks like it is nowhere to be seen now. As far as reproducing a raw IP pcap file, that might be done with tcprewrite, but it's been awhile since I've worked on the project that required it.

I think just mentioning to or warning the user that the pcap file is unsupported for unmodified playback might be ok so long as there is a hint on converting it to a format it can play.

**Comment by fklassen** [comment] 2017-03-06 21:55
@leonexis Leo, thanks for looking. I'll have a look at getting a warning for unsupported formats for version 4.2.

**Comment by fklassen** [comment] 2017-03-20 22:44
Hold for future release. Waiting for a raw PCAP.

**Comment by fklassen** [comment] 2018-01-26 02:30
Unable to reproduce. Closing for now.

**Closed by fklassen** 2018-01-26 02:30 UTC
Labels: enhancement, info

**Comment by bastienvty** [comment] 2023-03-09 10:27
@fklassen You can find this dataset (https://www.caida.org/catalog/datasets/request_user_info_forms/passive_dataset_request/) that are anonymized pcap files (raw ip). You just have to request access to get it. 

Unfortunately the command that @leonexis gave doesn't work (see similar issue #792).

**Comment by fklassen** [comment] 2023-03-11 02:55
> @fklassen You can find this dataset (https://www.caida.org/catalog/datasets/request_user_info_forms/passive_dataset_request/) that are anonymized pcap files (raw ip). You just have to request access to get it.
> 

I'll start work on this on the weekend. Unfortunately I cannot fill in the form without viloating my company's policies. Can you zip up the files and just add them to this ticket?

> Unfortunately the command that @leonexis gave doesn't work (see similar issue #792).

**Comment by bastienvty** [comment] 2023-03-11 13:25
I'm sorry but unfortunately I can't share the dataset as indicated in the AAA.
