### ISSUE TITLE
Diminished speed with high loop counts (probable bug)

### ISSUE THREAD

**Issue by JohnMcHugh** [appneta/tcpreplay#241] opened 2016-02-22 18:18 UTC
I'm running tcpreplay 4.1.0 with the following version information:
tcpreplay version: 4.1.0 (build git:v4.1.0)
Copyright 2013-2014 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta Inc.
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.5.3
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Packet editing: disabled
Fragroute engine: disabled
Injection method: PF_PACKET send()
Not compiled with netmap

I have a file with about 8GB of pcap containing 7012541 packets coming from a live capture that covers an 8 hour period on our corporate network.  As far as I can tell, there is nothing particularly special about the data except that it was captured in a situation where the MTU at capture exceeds the 9000 byte limit on the playback interface.  This results in 115 dropped packets per loop iteration, but that makes no difference since the test is simply a stress test of a new sensing system that is suspected of having memory leaks.

I preload the file and repeat it indefinitely using the following command:
```
nohup tcpreplay -i eno2 -K --no-flow-stats --stats=30 --topspeed --loop=0 --unique-ip \
            all-capture-20150402-00-07.pcap 2> all-capture-20150402-00-07-topspeed-err.txt \
            > all-capture-20150402-00-07-topspeed-log.txt &
```
A single iteration of the loop takes about 61 seconds and usually results in a data rate in the 960-970 Mbps rate as reported by 30 second statistics.  The link for the output device, eno2, is a 1Gbps link that is directly connected to the corresponding interface on the sensor machine.  Both are Intel interfaces and intel drivers are used.  For the first 4 hours or so of the test, the data rate remains approximately constant in the 968 Mbps range.  At 15240 seconds, the rate drops to near zero (less than 1Mbps) and slowly climbs reaching 484 Mbps at 30450 seconds where it again collapses. The pattern repeats with each recovery being lower that the previous one. The .png file is a graphic of the behavior, the .txt file is the elapsed time / Mbps file (comma separated) that produced this.  I have the transcript from the sensor, as well, if it would help.  The pcap file is 8GB and cannot be publicly distributes, but could be available on a non-distribution basis.
![tcpreplay-speed](https://cloud.githubusercontent.com/assets/576758/13227807/6e3c19c4-d966-11e5-9da5-8d57cd1be9ed.png)

[tcpreplay-speed.txt](https://github.com/appneta/tcpreplay/files/141137/tcpreplay-speed.txt)

**Comment by fklassen** [comment] 2016-02-23 00:03
Sounds like a bug, but may be hard for me to reproduce. What OS are you using?

Is it possible to try a couple things?

1. Try version 4.1.1. I did a fix that increased performance for `--topspeed`.
2. Have a look at your memory to see if it is being consumed due to a memory leak. On Linux I use `free -m` and look at the 2nd line.

**Comment by fklassen** [comment] 2016-02-23 00:19
Did a bit more investigation. I suspect #191 fixed the issue for v4.1.1.

**Comment by JohnMcHugh** [comment] 2016-02-23 14:00
Thank you very much.

The linux release is CentOS Linux release 7.0.1406 (Core)

I will install 4.1.1 and try again.  I ran “top” during operation and, as I recall, the memory used stayed in the 25% range.  The machine has 32GB, so this seems to be consistent with a 7.6 GB file.  I will monitor the usage more closely during this run.

================ On a possible additional bug.

I have had one other looping issue that I have not had time to look far enough into to submit a report, but I have seen evidence of a small number of duplicate packets with loop counts in the 20+ range using -K and —unique-ip.  I have a file with 10M packets, all 64 byte ICMP pings.  All have the same source address and the dst addresses start at 0.0.0.1 and increase by one for each packet.  The packets are being processed by a flow collector and should generate a unique flow for each packet.  With high loop counts, I a few less flows than expected, but when I add up the packet counts in the flow records, the total matches the number of packets sent.  Repeating the tests with a similarly constructed 100M packet file and 1/10 the loop count gives the “correct” result, 1 flow for each packet.

The difficulty in characterizing the problem exactly is that the flows timeout after 42 seconds of inactivity and the test is constructed to run for about 200 seconds at various speeds (manipulating the Mbps and loop counts to keep test time constant.  To get multiple packets into a flow, the duplicate(s) must occur within 42 seconds of the previous packet in the flow.

John McHugh

**Comment by JohnMcHugh** [comment] 2016-02-23 15:20
I have built 4.1.1 on the system and am repeating the test.  The 15000+ second point where the earlier test collapsed should be reached about 2:15 PM (EST) this afternoon.  It is now 10:20 AM.

I am capturing a log with free -m output every 30 seconds, as well.

John McHugh

**Comment by fklassen** [comment] 2016-02-23 16:36
OK.

Please open a new bug log for the 2nd issue and I'll have a look at it. If you can isolate the offending packets in a capture file it would be helpful. I may have a workaround but I won't discuss it in this bug log.

**Comment by JohnMcHugh** [comment] 2016-02-23 19:29
Test is still running, but we passed the 16000 second mark still running strong
```
Actual: 1823359419 packets (1939376571346 bytes) sent in 16020.01 seconds.
Rated: 121058400.0 Bps, 968.46 Mbps, 113816.51 pps

Tue Feb 23 14:28:27 EST 2016
             total       used       free     shared    buffers     cached
Mem:         31972      15638      16334         48          1       7618
```
I'm going to let it go at least until morning, but 4.1.1 seems to have solved the problem.

**Comment by fklassen** [comment] 2016-02-24 00:30
:+1:

**Comment by fklassen** [comment] 2016-02-24 00:34
BTW, when using free, you are missing the most important line of data. The second line will show the 16334 MB memory minus the 7618 MB cached. The cached is memory that is available to the kernel/OS, but is held for things like file cache. In reality you have much more than 16334 MB free.

**Comment by JohnMcHugh** [comment] 2016-02-24 15:06
Thanks.  I'll change the logging next time.  We ran for almost 24 hours and then shut it down to do some other testing. The last stats report before we shut it down was
Actual: 9646369785 packets (10260158012909 bytes) sent in 84660.08 seconds.
Rated: 121191200.0 Bps, 969.52 Mbps, 113941.31 pps
I'm going to get the rates from the entire log and do the plot to make sure I did not miss something

**Comment by fklassen** [comment] 2016-02-24 17:43
Looks pretty good. I'll keep this issue open for a while so you can complete testing.

BTW, also with v4.1.1 comes greatly improved performance for tcpreplay-edit. If you prefer, you can use random addresses rather than using --unique-ip.

**Comment by fklassen** [comment] 2016-04-26 18:34
Looks like no further issues. Closing.

**Closed by fklassen** 2016-04-26 18:34 UTC
Labels: 4.1.2, bug
