### ISSUE TITLE
[Bug] tcprewrite on Linux Cooked Capture hits fatal error in edit_packet.c:fix_ipv4_checksums()

### ISSUE THREAD

**Issue by msi3na** [appneta/tcpreplay#792] opened 2023-03-03 09:33 UTC
Trying tcprewrite to remove Linux Cooked Capture, but it hits a fatal error with an apparently well formed TCP packet over IP (all checksums are correct). Output is an empty pcap.

Command
tcprewrite --dlt=enet -i test_1.pcap -o test_2.pcap   

Error
Fatal Error: Error rewriting packets: From edit_packet.c:fix_ipv4_checksums() line 75:
Invalid packet: Expected IPv4 packet: got 0: pkt=1

Attachments
[Archive 3.zip](https://github.com/appneta/tcpreplay/files/10880521/Archive.3.zip)

Tried on both versions below:

-- MAC OS homebrew
tcprewrite version: 4.4.3 (build git:v4.4.3)
Copyright 2013-2022 by Fred Klassen - AppNeta
Copyright 2000-2012 by Aaron Turner
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Compiled against libdnet: 1.14
Compiled against libpcap: 1.10.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Fragroute engine: enabled

-- Ubuntu 20.4 LTS
tcprewrite version: 4.4.1 (build git:v4.4.1)
Copyright 2013-2022 by Fred Klassen - AppNeta
Copyright 2000-2012 by Aaron Turner
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.9.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Fragroute engine: disabled

![image](https://user-images.githubusercontent.com/92431617/222684471-0628a6dc-6daf-4879-b5ed-5d15fbab15d4.png)

**Comment by bastienvty** [comment] 2023-03-09 08:21
I have the same problem with raw ip packets. Did you find something @msi3na ?

**Comment by fklassen** [comment] 2023-06-10 22:57
SLL is not currently supported. This is a feature, not a bug. We are targeting SLL for 4.5, and probably will include PR #728

**Comment by fklassen** [comment] 2024-06-08 19:58
Was able to reproduce. Fixed in PR #873

**Closed by fklassen** 2024-06-08 19:58 UTC
Labels: bug
