### ISSUE TITLE
Tcpreplay with  --netmap option never finishes

### ISSUE THREAD

**Issue by jklm7** [appneta/tcpreplay#417] opened 2017-09-16 00:41 UTC
Hi,
I installed tcpreplay-4.2.6 with last version of netmap on CentOS Linux release 7.3.1611.

Commande blow never finishes, I I have to kill the tcpreplay 👍 
[root@localhost TRS]# /local/tcpreplay-4.2.6/src/tcpreplay  --intf1=ens4f0  -t -K  -l 10000  --netmap  BIP_DL620_to10150015.pcap
Switching network driver for ens4f0 to netmap bypass mode... done!
File Cache is enabled
Killed

- BIP_DL620_to10150015.pcap  : contains one  Ethernet packet of 620 bytes
- Packets sent by tcprepaly  are received on remote host
 - on tcpreplay build phase i obtain this warning : 
[root@localhost tcpreplay-4.2.6]#  ./configure --with-netmap=/local/netmap
....
checking net/netmap_user.h usability... no
checking net/netmap_user.h presence... yes
configure: WARNING: net/netmap_user.h: present but cannot be compiled
configure: WARNING: net/netmap_user.h:     check for missing prerequisite headers?
configure: WARNING: net/netmap_user.h: see the Autoconf documentation
configure: WARNING: net/netmap_user.h:     section "Present But Cannot Be Compiled"
configure: WARNING: net/netmap_user.h: proceeding with the compiler's result
configure: WARNING:     ## ---------------------------------------------------------- ##
configure: WARNING:     ## Report this to https://github.com/appneta/tcpreplay/issues ##
configure: WARNING:     ## ---------------------------------------------------------- ##
checking for net/netmap_user.h... no
...
...

##########################################################################
             TCPREPLAY Suite Configuration Results (4.2.6)
##########################################################################
libpcap:                    /usr (>= 0.9.6)
PF_RING libpcap             no   
libdnet:                    no   
autogen:                     (unknown - man pages will not be built)
Use libopts tearoff:        yes
64bit counter support:      yes
tcpdump binary path:        /usr/sbin/tcpdump
fragroute support:          no
tcpbridge support:          yes
tcpliveplay support:        yes

Supported Packet Injection Methods (*):
Linux TX_RING:              no
Linux PF_PACKET:            yes
BSD BPF:                    no
libdnet:                    no
pcap_inject:                yes
pcap_sendpacket:            yes **
pcap_netmap                 no
Linux/BSD netmap:           yes /local/netmap
Tuntap device support:      yes

I hope I have given all the info, thank you for you help
BR
Bil

**Comment by jklm7** [comment] 2017-09-16 13:48
tcpreplay with --netmap option and infinite loop , can interrupt, seems works, I can reach 9,77 Gbps

[root@localhost TRS]# /local/tcpreplay-4.2.6/src/tcpreplay  --intf1=ens4f0  -t -K  -l 0 --nm-delay=20 --netmap BIP_DL1000x1024_to10150015.pcap     
Switching network driver for ens4f0 to netmap bypass mode... done!
File Cache is enabled
^C User interrupt...
sendpacket_abort
Warning: Unable to send packet: Only able to write 0 bytes out of 1024 bytes total
Actual: 509795666 packets (522030761984 bytes) sent in 427.44 seconds
Rated: 1221278856.2 Bps, 9770.23 Mbps, 1192655.13 pps
Statistics for network device: ens4f0
        Successful packets:        509795665
        Failed packets:            0
        Truncated packets:         1
        Retried packets (ENOBUFS): 0
        Retried packets (EAGAIN):  973324594

**Comment by fklassen** [comment] 2017-09-17 21:50
Haven't seen this before. I'll look into it. Maybe something has changed with netmap.

**Comment by fklassen** [comment] 2018-01-26 03:45
It appears that the issue is not a bug. The options `-l 0` will force a continual loop.

The warning issue has been resolved in 4.3 beta1 release.

**Closed by fklassen** 2018-01-26 03:45 UTC
Labels: bug
