### ISSUE TITLE
errror when make

### ISSUE THREAD

**Issue by dreamyphone** [appneta/tcpreplay#628] opened 2020-12-22 10:23 UTC
`Making all in tcpedit`
make[3]: Entering directory /tmp/appneta-tcpreplay-72dcf55/src/tcpedit
Makefile:714: %reldir%/dlt_en10mb/Makefile.am: No such file or directory
Makefile:715: %reldir%/dlt_hdlc/Makefile.am: No such file or directory
Makefile:716: %reldir%/dlt_user/Makefile.am: No such file or directory
Makefile:717: %reldir%/dlt_raw/Makefile.am: No such file or directory
Makefile:718: %reldir%/dlt_null/Makefile.am: No such file or directory
Makefile:719: %reldir%/dlt_loop/Makefile.am: No such file or directory
Makefile:720: %reldir%/dlt_linuxsll/Makefile.am: No such file or directory
Makefile:721: %reldir%/dlt_ieee80211/Makefile.am: No such file or directory
Makefile:722: %reldir%/dlt_radiotap/Makefile.am: No such file or directory
Makefile:723: %reldir%/dlt_jnpr_ether/Makefile.am: No such file or directory
Makefile:724: %reldir%/dlt_pppserial/Makefile.am: No such file or directory
make[3]: *** No rule to make target `%reldir%/dlt_pppserial/Makefile.am'.  Stop.
make[3]: Leaving directory `/tmp/appneta-tcpreplay-72dcf55/src/tcpedit'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/appneta-tcpreplay-72dcf55/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/tmp/appneta-tcpreplay-72dcf55/src'
make: *** [all-recursive] Error 1`

**Comment by yinduren** [comment] 2020-12-25 03:32
It's the same with https://github.com/appneta/tcpreplay/issues/553

**Comment by fklassen** [comment] 2021-03-14 18:20
closed as duplicate of #553

**Closed by fklassen** 2021-03-14 18:20 UTC
Labels: duplicate
