### ISSUE TITLE
duplicated packets with tcpbridge

### ISSUE THREAD

**Issue by Nidhoggrr** [appneta/tcpreplay#539] opened 2019-02-13 13:36 UTC
tcpbridge duplicates all packets (seen on others systems). I am changing destination ip to 255^4 and destination mac to FF^6 and using unidirectional mode from one interface card to another

is this reproducable?

**Comment by fklassen** [comment] 2019-02-13 17:03
I don't understand the question. Please be more specific.

**Comment by schoberw** [comment] 2019-04-23 21:20
We see the same behavior on a Ubuntu 12.04 host running nested on KVM. We do not see this when running native on the KVM host. 

The main difference ist the driver used in the Ubuntu: e1000 qemu emulation. This cannot be changed because the Ubuntu crashes with virtio used.

When tcpbridge‘ing from a tap of a virtual machine to a real network i/f all is ok.

When tcpbridge“ing from a tap of a virtual machine to that e1000 the packets taken from the VM are sent twice out the destination interface (e.g. eth2 in our case).

tcpdump started with the same capture filters see the packets a single time on VM.

Stopping tcpbridge no more packets are seen on eth2. Double checked that tcpbridge is not running twice, too.

Any ideas what can tcpbridge causing it to send the packet a 2nd time? 

Br Walter

tcpdump started on eth2 sees the packets twice - and they are really sent twice as they indeed arrive twice on the destination sniffer host.

**Comment by fklassen** [comment] 2019-04-23 22:11
Labeling as a bug and will attempt to reproduce. No idea why it would be happening.

**Comment by schoberw** [comment] 2019-04-24 06:46
FTR: this is the command running:

`/usr/bin/tcpbridge -i mgc1.mp2 -I eth2 -u -x F:(udp or sctp) and (net 100.64.112.0/24 or host 100.64.65.154)`

It can be reproduced in my setup with

`tcpreplay -d 5 -i eth2 -L 10 testing.pcap`

having a 

`tcpdump -n -i eth2 -s 0 -w replay.pcap`

running in parallel. That tcpdump shows:

tcpdump: listening on eth2, link-type EN10MB (Ethernet), capture size 262144 bytes
^C20 packets captured
20 packets received by filter
0 packets dropped by kernel

=> 10 packets (-L 10) sent but 20 packets received. And indeed they are doubled in the replay.pcap.

Maybe this debug output helps:

```
DEBUG1 in sendpacket.c:sendpacket_open_pf() line 617: sendpacket: using PF_PACKET
DEBUG5 in utils.c:_our_safe_malloc() line 66: Malloc'd 1152 bytes in sendpacket.c:sendpacket_open_pf() line 690
sending out eth2
processing file: testing.pcap
DEBUG2 in send_packets.c:send_packets() line 138: packet 1 caplen 139
DEBUG4 in send_packets.c:do_sleep() line 360: Adjuster: 0s 0nsec
DEBUG4 in send_packets.c:do_sleep() line 383: This packet time: 1556087629s 663567usec
DEBUG4 in send_packets.c:do_sleep() line 384: Last packet time: 0s 0usec
DEBUG4 in send_packets.c:do_sleep() line 389: Now time: 1556088066s 348149usec
DEBUG2 in send_packets.c:do_sleep() line 494: nap_time before rounding:   0s 0nsec
DEBUG2 in send_packets.c:do_sleep() line 532: nap_time before delta calc: 0s 0nsec
DEBUG2 in send_packets.c:do_sleep() line 534: delta:                      0s 0nsec
DEBUG2 in send_packets.c:do_sleep() line 555: Sleeping:                   0s 0nsec
DEBUG2 in send_packets.c:send_packets() line 174: Sending packet #1
DEBUG2 in send_packets.c:send_packets() line 138: packet 2 caplen 98
DEBUG4 in send_packets.c:do_sleep() line 360: Adjuster: 0s 0nsec
DEBUG4 in send_packets.c:do_sleep() line 383: This packet time: 1556087629s 669766usec
DEBUG4 in send_packets.c:do_sleep() line 384: Last packet time: 1556087629s 663567usec
DEBUG4 in send_packets.c:do_sleep() line 389: Now time: 1556088066s 353827usec
DEBUG3 in send_packets.c:do_sleep() line 420: original packet delta time: 0s 6199usec
DEBUG3 in send_packets.c:do_sleep() line 423: original packet delta timv: 0s 6199000nsec
DEBUG3 in send_packets.c:do_sleep() line 425: original packet delta/div: 0s 6199000nsec
DEBUG2 in send_packets.c:do_sleep() line 494: nap_time before rounding:   0s 6199000nsec
DEBUG2 in send_packets.c:do_sleep() line 532: nap_time before delta calc: 0s 6199000nsec
DEBUG2 in send_packets.c:do_sleep() line 534: delta:                      0s 4759000nsec
DEBUG3 in send_packets.c:do_sleep() line 539: timesub: 0 4759000
DEBUG2 in send_packets.c:do_sleep() line 555: Sleeping:                   0s 1440000nsec
DEBUG4 in send_packets.c:do_sleep() line 621: Total sleep time: 0s 0usec
DEBUG2 in send_packets.c:do_sleep() line 624: sleep delta: 0s 4759000nsec
DEBUG2 in send_packets.c:send_packets() line 174: Sending packet #2
DEBUG2 in send_packets.c:send_packets() line 138: packet 3 caplen 139
DEBUG4 in send_packets.c:do_sleep() line 360: Adjuster: 0s 0nsec
DEBUG4 in send_packets.c:do_sleep() line 383: This packet time: 1556087630s 183542usec
DEBUG4 in send_packets.c:do_sleep() line 384: Last packet time: 1556087629s 669766usec
DEBUG4 in send_packets.c:do_sleep() line 389: Now time: 1556088066s 359626usec
DEBUG3 in send_packets.c:do_sleep() line 420: original packet delta time: 0s 513776usec
DEBUG3 in send_packets.c:do_sleep() line 423: original packet delta timv: 0s 513776000nsec
DEBUG3 in send_packets.c:do_sleep() line 425: original packet delta/div: 0s 513776000nsec
DEBUG2 in send_packets.c:do_sleep() line 494: nap_time before rounding:   0s 513776000nsec
DEBUG2 in send_packets.c:do_sleep() line 532: nap_time before delta calc: 0s 513776000nsec
DEBUG2 in send_packets.c:do_sleep() line 534: delta:                      0s 1959000nsec
DEBUG3 in send_packets.c:do_sleep() line 539: timesub: 0 1959000
DEBUG2 in send_packets.c:do_sleep() line 555: Sleeping:                   0s 511817000nsec
DEBUG4 in send_packets.c:do_sleep() line 621: Total sleep time: 0s 0usec
DEBUG2 in send_packets.c:do_sleep() line 624: sleep delta: 0s 1959000nsec
```

the last debug output says: 

`DEBUG2 in send_packets.c:send_packets() line 174: Sending packet #9`

So tcpreply believes it's sending 10 packet.

tcpreplay                        3.4.4-2+deb8u1build0.14.04.1
libpcap0.8                       1.5.3-2

```
tcpbridge version: 3.4.4 (build 2450) (debug)
Copyright 2000-2010 by Aaron Turner <aturner at synfin dot net>
Not compiled with libdnet.
Compiled against libpcap: 1.5.3
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Injection method: PF_PACKET send()
```

**Comment by fklassen** [comment] 2020-06-12 20:14
I am unable to recreate the issue on version 4.3.2. Maybe you want to use that version, or wait a week or so before I release 4.3.3. I don't have the exact setup you have, but version 3.4.4 is very old.

```
root@m70-ynm3t:~# tcpbridge -i eth0 -I eth1 -u -x "F:(udp or sctp) and net 192.168.50.0/24"
```

```
root@m35-r4mL5:~# tcpdump -i eth1
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth1, link-type EN10MB (Ethernet), capture size 262144 bytes
13:11:24.265924 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 284
13:11:24.266071 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 275
13:11:24.266090 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 327
13:11:24.266120 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 339
13:11:24.266120 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 341
13:11:24.266139 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 355
13:11:24.485896 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 284
13:11:24.485896 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 275
13:11:24.485928 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 327
13:11:24.485945 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 339
13:11:24.485962 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 341
13:11:24.485979 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 355
13:11:27.545939 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 284
13:11:27.545939 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 275
13:11:27.545987 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 327
13:11:27.545987 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 339
13:11:27.546009 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 341
13:11:27.546009 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 355
13:11:27.755890 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 284
13:11:27.755890 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 275
13:11:27.755935 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 327
13:11:27.755935 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 339
13:11:27.755957 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 341
13:11:27.755957 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 355
13:11:29.795933 IP 192.168.50.214.17500 > 255.255.255.255.17500: UDP, length 145
13:11:29.795939 IP 192.168.50.214.17500 > 192.168.50.255.17500: UDP, length 145
13:11:30.815941 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 284
13:11:30.815942 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 275
13:11:30.815987 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 327
13:11:30.815987 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 339
13:11:30.816009 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 341
13:11:30.816009 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 355
13:11:31.025886 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 284
13:11:31.025886 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 275
13:11:31.025930 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 327
13:11:31.025930 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 339
13:11:31.025952 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 341
13:11:31.025952 IP RT-AC86U-69A8.58878 > 239.255.255.250.1900: UDP, length 355
```

**Comment by schoberw** [comment] 2020-06-14 08:17
Thanks for retry. I guess this is really a corner case on that old Ubuntu 12.04 running as XEN host nested on KVM (due to the requirments of an old App).

If this is not reproducable anymore we could close this issue with "corner case".

**Comment by fklassen** [comment] 2020-06-14 20:26
> If this is not reproducable anymore we could close this issue with "corner case".

Closing for now, can be reopened again if it comes back.

**Closed by fklassen** 2020-06-14 20:26 UTC
Labels: bug
