### ISSUE TITLE
Restore STDIN to blocking mode upon termination

### ISSUE THREAD

**Issue by recvfrom** [appneta/tcpreplay#470] opened 2018-04-16 21:54 UTC
I've been having some problems with STDIN getting set to non-blocking mode, breaking several other commands run in that same terminal window:

https://unix.stackexchange.com/questions/437409/problems-caused-by-stdin-set-to-non-blocking-mode

I wrote a program to detect when this change happens and found that tcpreplay appears to be a cause:

```
$ /usr/bin/tcprewrite --version
tcprewrite version: 4.2.6 (build git:v4.2.6) (debug)
Copyright 2013-2017 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Not compiled with libdnet.
Compiled against libpcap: 1.8.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Fragroute engine: disabled
Warning, STDIN in nonblock mode
$
```

Could tcpreplay be updated to restore the flags on STDIN (and maybe STDOUT / STDERR, if needed) upon termination?  Thanks!

**Comment by fklassen** [comment] 2018-04-16 23:08
Yeah, that should get cleaned up. Logging as a bug.

**Comment by recvfrom** [comment] 2018-04-17 19:04
I modified my test program to check STDOUT and STDERR as well, and can confirm that they also get left in non-blocking mode

```
$ cat /proc/self/fdinfo/0 
pos:	0
flags:	0100002
mnt_id:	25
$ cat /proc/self/fdinfo/1
pos:	0
flags:	0100002
mnt_id:	25
$ cat /proc/self/fdinfo/2
pos:	0
flags:	0100002
mnt_id:	25
$ tcprewrite --version
tcprewrite version: 4.2.6 (build git:v4.2.6-4-g54da3478)
Copyright 2013-2017 by Fred Klassen <tcpreplay at appneta dot com> - AppNeta
Copyright 2000-2012 by Aaron Turner <aturner at synfin dot net>
The entire Tcpreplay Suite is licensed under the GPLv3
Cache file supported: 04
Compiled against libdnet: 1.12
Compiled against libpcap: 1.8.1
64 bit packet counters: enabled
Verbose printing via tcpdump: enabled
Fragroute engine: enabled
$ cat /proc/self/fdinfo/0 
pos:	0
flags:	0104002
mnt_id:	25
$ cat /proc/self/fdinfo/1
pos:	0
flags:	0104002
mnt_id:	25
$ cat /proc/self/fdinfo/2
pos:	0
flags:	0104002
mnt_id:	25
```

**Comment by fklassen** [comment] 2018-10-21 18:57
duplicate of #416

**Closed by fklassen** 2018-10-21 18:57 UTC
Labels: duplicate
